[package]
name = "raytracer"
version = "0.1.0"
authors = ["Blair Fitzhugh <bfitz1@umbc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.12.0"
rand = "0.7.0"